;               HCC FIG generic 8086 FORTH
; $Id$
; Copyright (2000): Albert van der Horst, HCC FIG Holland by GNU Public License

REM Generates a bootable disk from a TASM/MASM forth with BIOS i/o in %1.

ECHO FLOPPY A: WILL BECOME A FORTH BOOTABLE DISK
ECHO ALL DATA WILL BE LOST!
ECHO HIT ^C IF YOU WANT TO STOP.
PAUSE

Tasm/la/zi %1
REM Equally possible:
REM masm %1     
tlink/v %1

echo N > \tmp\fminput.$$$
echo N >> \tmp\fminput.$$$
echo N >> \tmp\fminput.$$$
Format a:/u <\tmp\fminput.$$$

COPY %1.exe forth.com
REM This remainder is probably usable for a FORTH.COM
REM generated by NASM.
echo N FORTH.COM> \tmp\dbinput.$$$
echo L >> \tmp\dbinput.$$$
echo W cs:200>> \tmp\dbinput.$$$
echo W cs:0 0 0 1>> \tmp\dbinput.$$$
echo Q>> \tmp\dbinput.$$$
DEBUG                < C:\tmp\dbinput.$$$

copy forth.com a:
REM SUCCESFULL ENDING
A:
ATTRIB +S +R +H FORTH.COM
C:
EXIT


